#
#  TDS: 11/2011
#  PROTOTYPE - PROTOTYPE - PROTOTYPE
#  If you are surprised to see this here, just ignore it.
#  Many fields are probably inaccurate.
#
Catkin-ProjectName: ros
Version: 0.0.1
Depends: catkin, rospack
Description: ROS Core
Author: Ken Conley et al
Maintainer: Ken Conley <kwc@willowgarage.com>
Homepage: http://www.ros.org

Catkin-CopyrightType: willowgarage
Catkin-DebRulesType: +rules.em
